"""create_initial_schema

Revision ID: 9df090091b69
Revises:
Create Date: 2026-09-09 17:26:39.915588

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9df090091b69"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "concepts",
        sa.Column(
            "id",
            sa.String(length=100),
            nullable=False,
            comment="Unique concept identifier, e.g. sql_inner_join",
        ),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column(
            "bloom_level",
            sa.Integer(),
            nullable=False,
            comment="Bloom taxonomy cognitive depth level (1-6)",
        ),
        sa.Column(
            "default_prior_l0",
            sa.Float(),
            nullable=False,
            comment="Initial mastery prior L_0 for beginner",
        ),
        sa.Column(
            "ebbinghaus_strength_base",
            sa.Float(),
            nullable=False,
            comment="Base memory half-life / stability S_0",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "students",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("is_guest", sa.Boolean(), nullable=False),
        sa.Column("frustration_index", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_active_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_students_email"), "students", ["email"], unique=True)
    op.create_table(
        "cognitive_states",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("concept_id", sa.String(length=100), nullable=False),
        sa.Column(
            "mastery_prob",
            sa.Float(),
            nullable=False,
            comment="P(L_t) probability of mastery from BKT",
        ),
        sa.Column(
            "memory_strength",
            sa.Float(),
            nullable=False,
            comment="S_i memory stability from Ebbinghaus curve",
        ),
        sa.Column(
            "retention_score",
            sa.Float(),
            nullable=False,
            comment="M_i(t) retention probability from Ebbinghaus",
        ),
        sa.Column("last_interacted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_attempts", sa.Integer(), nullable=False),
        sa.Column("successful_attempts", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["concept_id"], ["concepts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("student_id", "concept_id", name="uq_student_concept"),
    )
    op.create_index(
        op.f("ix_cognitive_states_concept_id"), "cognitive_states", ["concept_id"], unique=False
    )
    op.create_index(
        op.f("ix_cognitive_states_student_id"), "cognitive_states", ["student_id"], unique=False
    )
    op.create_table(
        "diagnostic_assessments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column(
            "responses",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Recorded responses to 5-7 adaptive placement questions",
        ),
        sa.Column(
            "inferred_k0",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Inferred mastery vector K_0 after DAG prerequisite propagation",
        ),
        sa.Column(
            "declared_profile",
            sa.String(length=50),
            nullable=False,
            comment="BEGINNER, INTERMEDIATE, ADVANCED, or TESTED",
        ),
        sa.Column("pre_test_score", sa.Float(), nullable=False),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_diagnostic_assessments_student_id"),
        "diagnostic_assessments",
        ["student_id"],
        unique=True,
    )
    op.create_table(
        "exercises",
        sa.Column(
            "id",
            sa.String(length=100),
            nullable=False,
            comment="Unique exercise ID, e.g. ex_join_null_01",
        ),
        sa.Column("concept_id", sa.String(length=100), nullable=False),
        sa.Column(
            "difficulty",
            sa.String(length=50),
            nullable=False,
            comment="BEGINNER, INTERMEDIATE, ADVANCED",
        ),
        sa.Column(
            "mode",
            sa.String(length=50),
            nullable=False,
            comment="LEARN_NEW, PRACTICE_REVIEW, DIAGNOSTIC",
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "schema_ddl",
            sa.Text(),
            nullable=False,
            comment="DDL statements to create SQLite sandbox tables",
        ),
        sa.Column(
            "seed_data_sql",
            sa.Text(),
            nullable=False,
            comment="INSERT statements to seed SQLite sandbox rows (< 100 rows)",
        ),
        sa.Column(
            "solution_sql",
            sa.Text(),
            nullable=False,
            comment="Standard reference SQL query for grading",
        ),
        sa.Column(
            "ast_constraints",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="sqlglot AST rules: required clauses, forbidden hardcoding",
        ),
        sa.Column(
            "progressive_hints",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="3 progressive levels of Socratic hints",
        ),
        sa.ForeignKeyConstraint(["concept_id"], ["concepts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_exercises_concept_id"), "exercises", ["concept_id"], unique=False)
    op.create_table(
        "prerequisites",
        sa.Column(
            "concept_id",
            sa.String(length=100),
            nullable=False,
            comment="Target concept requiring a prior concept",
        ),
        sa.Column(
            "prerequisite_id",
            sa.String(length=100),
            nullable=False,
            comment="Pre-requisite concept that must be mastered first",
        ),
        sa.ForeignKeyConstraint(["concept_id"], ["concepts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["prerequisite_id"], ["concepts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("concept_id", "prerequisite_id"),
    )
    op.create_table(
        "spot_checks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("exercise_id", sa.String(length=100), nullable=False),
        sa.Column(
            "question",
            sa.Text(),
            nullable=False,
            comment="Conceptual 30s verification question (e.g. 'Why use LEFT JOIN instead of INNER JOIN here?')",
        ),
        sa.Column(
            "options",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Array of 3-4 multiple-choice options",
        ),
        sa.Column(
            "correct_option_index",
            sa.Integer(),
            nullable=False,
            comment="0-indexed position of correct answer",
        ),
        sa.Column(
            "explanation",
            sa.Text(),
            nullable=False,
            comment="Socratic explanation shown after attempt",
        ),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_spot_checks_exercise_id"), "spot_checks", ["exercise_id"], unique=False
    )
    op.create_table(
        "submissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("exercise_id", sa.String(length=100), nullable=False),
        sa.Column("submitted_sql", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("ast_passed", sa.Boolean(), nullable=False),
        sa.Column("execution_time_ms", sa.Float(), nullable=False),
        sa.Column("ast_violations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_submissions_exercise_id"), "submissions", ["exercise_id"], unique=False
    )
    op.create_index(op.f("ix_submissions_student_id"), "submissions", ["student_id"], unique=False)
    op.create_table(
        "telemetry_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("exercise_id", sa.String(length=100), nullable=False),
        sa.Column(
            "time_spent_seconds",
            sa.Integer(),
            nullable=False,
            comment="Total interaction time on exercise workspace",
        ),
        sa.Column(
            "keystroke_count",
            sa.Integer(),
            nullable=False,
            comment="Total individual keyboard input events",
        ),
        sa.Column(
            "paste_events_count",
            sa.Integer(),
            nullable=False,
            comment="Number of clipboard paste occurrences",
        ),
        sa.Column(
            "min_paste_duration_ms",
            sa.Integer(),
            nullable=False,
            comment="Smallest duration measured between paste strokes (0ms = instant GenAI)",
        ),
        sa.Column(
            "tab_switches",
            sa.Integer(),
            nullable=False,
            comment="Blur/focus switches away from Monaco window",
        ),
        sa.Column(
            "flagged_suspicious",
            sa.Boolean(),
            nullable=False,
            comment="Flagged by heuristic: fast paste + tab switch + high length",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_telemetry_logs_exercise_id"), "telemetry_logs", ["exercise_id"], unique=False
    )
    op.create_index(
        op.f("ix_telemetry_logs_student_id"), "telemetry_logs", ["student_id"], unique=False
    )
    op.create_table(
        "spot_check_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("spot_check_id", sa.UUID(), nullable=False),
        sa.Column("selected_option_index", sa.Integer(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column(
            "response_time_seconds",
            sa.Integer(),
            nullable=False,
            comment="Time elapsed from modal popup to answer (< 30s expected)",
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["spot_check_id"], ["spot_checks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_spot_check_attempts_spot_check_id"),
        "spot_check_attempts",
        ["spot_check_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_spot_check_attempts_submission_id"),
        "spot_check_attempts",
        ["submission_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_spot_check_attempts_submission_id"), table_name="spot_check_attempts")
    op.drop_index(op.f("ix_spot_check_attempts_spot_check_id"), table_name="spot_check_attempts")
    op.drop_table("spot_check_attempts")
    op.drop_index(op.f("ix_telemetry_logs_student_id"), table_name="telemetry_logs")
    op.drop_index(op.f("ix_telemetry_logs_exercise_id"), table_name="telemetry_logs")
    op.drop_table("telemetry_logs")
    op.drop_index(op.f("ix_submissions_student_id"), table_name="submissions")
    op.drop_index(op.f("ix_submissions_exercise_id"), table_name="submissions")
    op.drop_table("submissions")
    op.drop_index(op.f("ix_spot_checks_exercise_id"), table_name="spot_checks")
    op.drop_table("spot_checks")
    op.drop_table("prerequisites")
    op.drop_index(op.f("ix_exercises_concept_id"), table_name="exercises")
    op.drop_table("exercises")
    op.drop_index(op.f("ix_diagnostic_assessments_student_id"), table_name="diagnostic_assessments")
    op.drop_table("diagnostic_assessments")
    op.drop_index(op.f("ix_cognitive_states_student_id"), table_name="cognitive_states")
    op.drop_index(op.f("ix_cognitive_states_concept_id"), table_name="cognitive_states")
    op.drop_table("cognitive_states")
    op.drop_index(op.f("ix_students_email"), table_name="students")
    op.drop_table("students")
    op.drop_table("concepts")
    # ### end Alembic commands ###
